## Estudo redes Neurais
**Objetivo:** implementação manual de uma rede perceptron

**História do algoritmo:**  
Em 1943, McCulloch e Pitts formularam o primeiro modelo matemático de um neurônio artificial: uma unidade lógica capaz de implementar portas como AND e OR. O problema que resolveram foi mostrar que o cérebro poderia ser descrito como um sistema lógico, mas sem qualquer capacidade de aprendizado, já que os pesos eram fixos.

Mais tarde, Donald Hebb (1949) propôs uma regra simples de atualização de conexões, mas ainda limitada. Foi então que Frank Rosenblatt, em 1958, criou o Perceptron, o primeiro modelo capaz de aprender automaticamente os pesos a partir de exemplos. O problema que ele se propunha a resolver era ir além da lógica fixa e permitir que uma máquina conseguisse ajustar sua fronteira de decisão para classificar padrões binários linearmente separáveis.

$$
\hat{y} = 
\begin{cases}
1, & \text{se } \sum_{i=1}^{n} w_i \cdot x_i + b \geq 0 \\
0, & \text{caso contrário}
\end{cases}
$$

In [1]:
import numpy as np

In [2]:
def calc_peso(weight, col, real, pred, ln):
    """Função para ajustar os pesos"""
    
    w_fin = weight+ln*(real - pred)*col
    return w_fin


In [3]:
def calc_bias(bias, predito, real, lr):
    
    """Função que calcula o bias"""

    return bias+lr*(predito - real)

In [4]:
def perceptron(X, y, lr, epocs):
    max_random_w = np.max(X)
    
    real = 0 
    pred = 0
    w = np.random.uniform(-2, 2, X.shape[1])
    pesos_hist = []
    epocs = range(epocs)
    b = np.random.uniform(0, 2, 1)[0]

    pesos_hist.append(w)
    pred_hist = []

    if isinstance(X, np.ndarray):
        for epoc in epocs:
            predicoes = []

            for i, row in enumerate(X):
 
                pred_col_row = 0
                for j, col in enumerate(row):
                    pred_col_row += w[j]*col

                pred_col_row += b             
                if pred_col_row > 0:
                    pred = 1
                else:
                    pred = 0


                predicoes.append(pred)
                if pred != y[i]:
                    pesos_hist.append(w)
                    w = np.array([calc_peso(w[j], col, y[i], pred, lr) for j, col in enumerate(row)])
                    b = calc_bias(b, pred, y[i], lr)

            pred_hist.append(predicoes)
                    
    return {"pesos":w, "predicoes":predicoes, "learning_rate":lr, "pesos_hist":pesos_hist}
        


In [5]:
X = np.array([
    [5, 20],
    [10, 40],
    [3, 12],
    [1, 5]
])
y = np.array([0, 0, 0, 1])

In [6]:
perceptron(X, y,  2, 200)

{'pesos': array([-89.32766012,  39.94193101]),
 'predicoes': [0, 0, 0, 0],
 'learning_rate': 2,
 'pesos_hist': [array([ 0.67233988, -0.05806899]),
  array([ 0.67233988, -0.05806899]),
  array([ -9.32766012, -40.05806899]),
  array([ -7.32766012, -30.05806899]),
  array([ -5.32766012, -20.05806899]),
  array([ -3.32766012, -10.05806899]),
  array([-1.32766012, -0.05806899]),
  array([0.67233988, 9.94193101]),
  array([ -9.32766012, -30.05806899]),
  array([ -7.32766012, -20.05806899]),
  array([ -5.32766012, -10.05806899]),
  array([-3.32766012, -0.05806899]),
  array([-1.32766012,  9.94193101]),
  array([-11.32766012, -30.05806899]),
  array([ -9.32766012, -20.05806899]),
  array([ -7.32766012, -10.05806899]),
  array([-5.32766012, -0.05806899]),
  array([-3.32766012,  9.94193101]),
  array([-13.32766012, -30.05806899]),
  array([-11.32766012, -20.05806899]),
  array([ -9.32766012, -10.05806899]),
  array([-7.32766012, -0.05806899]),
  array([-5.32766012,  9.94193101]),
  array([-15.32